- spaced-repetition-front-end/.gitignore
- spaced-repetition-front-end/package.json
- spaced-repetition-front-end/src/App.css
- spaced-repetition-front-end/src/App.js
- spaced-repetition-front-end/src/components/Card.js
- spaced-repetition-front-end/src/components/CardList.js
- spaced-repetition-front-end/src/components/Deck.js
- spaced-repetition-front-end/src/components/DeckList.js
- spaced-repetition-front-end/src/components/Header.js
- spaced-repetition-front-end/src/components/LandingPage.js
- spaced-repetition-front-end/src/components/Sidebar.js
- spaced-repetition-front-end/src/components/Wrapper.js
- spaced-repetition-front-end/src/components/auth/Login.jsx
- spaced-repetition-front-end/src/components/auth/LoginForm.jsx
- spaced-repetition-front-end/src/components/auth/RegistrationForm.jsx
- spaced-repetition-front-end/src/index.css
- spaced-repetition-front-end/src/index.js
- spaced-repetition-front-end/yarn.lock
Added Card, CardList, Deck, DeckList, Wrapper, Header, LandingPage, Sidebar components to build out the wireframe. Added basic styling. Added basic routing between components.
Incomplete/work-in-progress, PR is for discussion/feedback
> Front end branch

- spaced-repetition-front-end/.gitignore
- spaced-repetition-front-end/package.json
- spaced-repetition-front-end/src/App.css
- spaced-repetition-front-end/src/App.js
- spaced-repetition-front-end/src/components/Card.js
- spaced-repetition-front-end/src/components/CardList.js
- spaced-repetition-front-end/src/components/Deck.js
- spaced-repetition-front-end/src/components/DeckList.js
- spaced-repetition-front-end/src/components/Header.js
- spaced-repetition-front-end/src/components/LandingPage.js
- spaced-repetition-front-end/src/components/Sidebar.js
- spaced-repetition-front-end/src/components/Wrapper.js
- spaced-repetition-front-end/src/components/auth/Login.jsx
- spaced-repetition-front-end/src/components/auth/LoginForm.jsx
- spaced-repetition-front-end/src/components/auth/RegistrationForm.jsx
- spaced-repetition-front-end/src/index.css
- spaced-repetition-front-end/src/index.js
- spaced-repetition-front-end/yarn.lock
Using Okta token-based login and registration tools, a user can register or login. Upon successful registration or login, the user is redirected to their dashboard. Unsuccessful logins and registrations are not functional yet.
This change requires a documentation update
Incomplete/work-in-progress
Checklist:
> Okta register and login users on the frontend

- spaced-repetition-back-end/index.js
- spaced-repetition-back-end/package.json
- spaced-repetition-back-end/stripe/stripeRoutes.js
- spaced-repetition-back-end/yarn.lock
- spaced-repetition-front-end/package.json
- spaced-repetition-front-end/src/App.js
- spaced-repetition-front-end/src/components/Billing.js
- spaced-repetition-front-end/src/components/CheckoutForm.js
- spaced-repetition-front-end/yarn.lock
Added process.env conditional in stripeCheckout.js. To run in your local, secret key has to be in a .env in the root of spaced-repetition-back-end.
Bug fix (non-breaking change which fixes an issue)
> create process.env conditional for secret key

- spaced-repetition-front-end/src/App.js
- spaced-repetition-front-end/src/components/Card.js
- spaced-repetition-front-end/src/components/Deck.js
- spaced-repetition-front-end/src/components/TrainDeck.js
- spaced-repetition-front-end/yarn.lock
Intended as a WIP towards the deck training feature. A link on each deck in the deck list view routes the user to a training module. As of now, only the first card and the name of the deck are showing on this view. The "Answer" button sets the `trained` boolean to true, which then shows the answer and user options relating to the SRS algorithm.
Change status
Checklist:
> Sets up deck training capability from DeckList view

- spaced-repetition-back-end/yarn.lock
- spaced-repetition-front-end/src/components/Card.js
- spaced-repetition-front-end/src/components/Deck.js
Updates yarn.lock to exclude malicious package described in link below:
Fixes issue: https://github.com/dominictarr/event-stream/issues/116
Please delete options that are not relevant.
> Issue with event stream

- spaced-repetition-front-end/src/components/Card.js
- spaced-repetition-front-end/src/components/Deck.js
The next button changes a counter on state which is used to progress through the cards in a deck. When the counter is incremented, the current card values change to the next card. The last card to be trained shows end training session button instead of next button.
> Training mode iterates through the entire deck

- spaced-repetition-back-end/yarn.lock
- spaced-repetition-front-end/src/components/Card.js
- spaced-repetition-front-end/src/components/TrainDeck.js
- spaced-repetition-front-end/yarn.lock
Routes user back to the decks list view after training is completed, and also redirects user to decks list view if they decide to quit the session mid-way through. Quitting the session is available through an options button/menu in the card container. In the future, it can also house editing the card, etc. The next and end session buttons are only visible after the user has selected whether they missed or got the question.
Notes: This UX decision is not set in stone. Another option is to use a modal upon completion to prompt the user for what they want to do next (e.g. train the deck again, go to decks list view, etc). …
> Redirects user to deck list view when quitting session

- spaced-repetition-back-end/yarn.lock
- spaced-repetition-front-end/src/components/Card.js
- spaced-repetition-front-end/src/components/Deck.js
- spaced-repetition-front-end/src/components/TrainDeck.js
- spaced-repetition-front-end/yarn.lock
Basic modal styling for carousel-like UX when training decks. 
There may be merge conflicts when Saxon's PR is merged. Ping me after merging his, and I'll remedy any conflicts in my PR before merging it.
> Modal styling per feature spec - no RWD

- spaced-repetition-back-end/yarn.lock
- spaced-repetition-front-end/src/components/Card.js
- spaced-repetition-front-end/src/components/Deck.js
- spaced-repetition-front-end/src/components/TrainDeck.js
- spaced-repetition-front-end/yarn.lock
Basic responsiveness for the card view modal when training a deck. The breakpoint is set at 700px; he modal is not larger than 600px on larger screens and much of the modal content is already in good placement.
The only conflicts are those that pertain to the flat-stream issue from before. If that is even a problem by the time this is merged.
> Train deck modal basic - responsive web design

- .gitignore
- spaced-repetition-back-end/db/seeds/02-decks.js
- spaced-repetition-back-end/postgres_setup_help.txt
- spaced-repetition-back-end/routes/decks/decksRoutes.js
- spaced-repetition-front-end/src/App.js
- spaced-repetition-front-end/src/components/Card.js
- spaced-repetition-front-end/src/components/DeckList.js
- spaced-repetition-front-end/src/components/TrainDeck.js
This sets up the location and functions for updating card progress while using the TrainDeck component.
To reduce calls to server, cards are sent in a batch and when trigger when an interval of time has passed after finishing a card. If another card is completed before the timeout is done, the timeout resets and the card is added to the batch. 
This allows user progress to be saved even if the user forgets to hit the Save button when navigating away from the page. 
TO DO: In POST request in decksRoutes.js, make a function call to algorithm.js and save the new data. Need to meet with team to discuss where and how this should be saved since we are not using a Users table. If each user's progress is stored on each card, we need to make sure that in our GET requests we strip out the progress …
> Setup POST for card progress batch updating on frontEnd and backEnd

- spaced-repetition-back-end/index.js
- spaced-repetition-front-end/src/components/CheckoutForm.js
Fixed environment variable name, made routes consistent.
Bug fix (non-breaking change which fixes an issue)
> fix stripe env var and routes

- spaced-repetition-back-end/db/migrations/20181127134939_users.js
- spaced-repetition-back-end/index.js
- spaced-repetition-back-end/routes/cards/cardsRoutes.js
- spaced-repetition-back-end/routes/users/usersModel.js
- spaced-repetition-back-end/routes/users/usersRoutes.js
- spaced-repetition-front-end/src/App.js
- spaced-repetition-front-end/src/components/AddDeck.js
- spaced-repetition-front-end/src/components/CardInputs.js
- spaced-repetition-front-end/src/components/CheckoutForm.js
@affordances, @DrewMoody @gooseandmegander @noxasaxon 
created user table in postgres, route to create/update user, route to update tier (paid, free). Connected to front end on login, will now automatically create a user if it doesnt exist. 
Drew worked on routes to create decks as well
> users routes and table, create decks

- spaced-repetition-back-end/db/migrations/20181127184254_add_stripe_customer_id_to_users.js
- spaced-repetition-back-end/index.js
- spaced-repetition-back-end/routes/decks/decksRoutes.js
- spaced-repetition-back-end/routes/stripe/stripeRoutes.js
- spaced-repetition-back-end/routes/users/usersModel.js
- spaced-repetition-back-end/routes/users/usersRoutes.js
- spaced-repetition-back-end/stripe/stripeRoutes.js
- spaced-repetition-front-end/src/App.js
- spaced-repetition-front-end/src/components/Billing.js
- spaced-repetition-front-end/src/components/CheckoutForm.js
Adds full subscription and cancellation functionality for Stripe. When 'buy now' is clicked: customer and subscription are added to Stripe dashboard; in users table, tier is changed to 'paid' and Stripe customer id is set; in App state, profile.tier is updated. When 'cancel' is clicked: customer (and subscription) are deleted from Stripe dashboard; in user's table, tier is changed to 'free' and Stripe customer id is changed to null; in App state, profile.tier is updated.
> Stripe cancellation

- spaced-repetition-front-end/src/components/AddDeck.js
- spaced-repetition-front-end/src/components/CardInputs.js
Implemented the ability to dynamically add new cards to a deck, and submit everything at once. This PR is for functionality. It has not yet been styled.
> 
> ## Change status
> Dynamic add cards

- spaced-repetition-front-end/src/App.js
- spaced-repetition-front-end/src/components/Billing.js
- spaced-repetition-front-end/src/components/Deck.js
- spaced-repetition-front-end/src/components/Header.js
- spaced-repetition-front-end/src/components/Profile.js
- spaced-repetition-front-end/src/components/Sidebar.js
Profile is now accessible from the Sidebar, with Billing now at the bottom of Profile.
Bug fix (non-breaking change which fixes an issue)
> add Profile to Sidebar, add Billing to Profile

- spaced-repetition-front-end/src/App.js
- spaced-repetition-front-end/src/components/Billing.js
- spaced-repetition-front-end/src/components/DeckList.js
- spaced-repetition-front-end/src/components/Header.js
- spaced-repetition-front-end/src/components/Profile.js
- spaced-repetition-front-end/src/components/Sidebar.js
- spaced-repetition-front-end/src/components/Wrapper.js
Mostly added `width:100%` for resizing. Changes affect dashboard, decklist, and profile view since those are the ones currently showing correctly.
> Adds basic responsiveness to current working pages

- spaced-repetition-front-end/src/components/AddDeck.js
- spaced-repetition-front-end/src/components/CardInputs.js
- spaced-repetition-front-end/src/components/Sidebar.js
Got rid of the need for a save button on each individual card
> Add deck UX changes

- spaced-repetition-front-end/src/App.js
- spaced-repetition-front-end/src/components/AddCard.js
- spaced-repetition-front-end/src/components/Card.js
- spaced-repetition-front-end/src/components/CardList.js
- spaced-repetition-front-end/src/components/Deck.js
- spaced-repetition-front-end/src/components/DeckList.js
- spaced-repetition-front-end/src/components/DeckView.js
Styling update for DeckList, clicking a deck takes you to DeckView component where you can view all the cards in that deck (based off Megan's CardsList component), Add Card button works in this component (removes deck selection in adding card)
> View Single Deck, Add Card works in View Deck, styled Deck List

- spaced-repetition-front-end/src/components/Card.js
- spaced-repetition-front-end/src/components/Deck.js
- spaced-repetition-front-end/src/components/DeckView.js
- spaced-repetition-front-end/src/components/EditDeck.js
- spaced-repetition-front-end/src/components/Profile.js
Josh's UI tips:
DECK: lined up training dueDate and tags container with buttons
DECKVIEW: added padding
CARD: remove white border, emphasize card item field descriptions (WIP)
LANDINGPAGE: compressed and reduced size of background image (squoosh.app)
---
Bugfixes:
DECK: Edit button did not work correctly, added e.stopPropagation
--
features:
conditional render delete button on Deck
removed add Deck from sidebar
add deck now in toolbar under DeckList
styled SVGs for sidebar
> WIP fixing/styling add deck. CopyToClipboard Works, bugfixes and UI fixes listed in description

- spaced-repetition-front-end/src/components/LandingPage/Features.js
- spaced-repetition-front-end/src/components/LandingPage/LandingPage.js
- spaced-repetition-front-end/src/components/LandingPage/Pricing.js
- spaced-repetition-front-end/src/components/LandingPage/WhySpacedReps.js
Adds fully styled version of desktop layout page to the landing page view.
Adding responsiveness for smaller devices now.
Please delete options that are not relevant.
*end PR template*
[Ryan Holdaway](https://github.com/rholdy)
> Landing Page - pricing section desktop layout

- spaced-repetition-front-end/src/components/LandingPage/LandingPage.js
- spaced-repetition-front-end/src/components/LandingPage/Pricing.js
Pricing view uses mostly 900px and 600px media queries along with percentage-based layout to create responsive view.
*end PR template*
[Ryan Holdaway](https://github.com/rholdy)
> Pricing view on Landing Page responsive on smaller devices

- spaced-repetition-front-end/src/App.js
- spaced-repetition-front-end/src/components/AddDeck.js
- spaced-repetition-front-end/src/components/Billing.js
- spaced-repetition-front-end/src/components/CardList.js
- spaced-repetition-front-end/src/components/CheckoutForm.js
- spaced-repetition-front-end/src/components/DeckList.js
- spaced-repetition-front-end/src/components/LandingPage/Pricing.js
- spaced-repetition-front-end/src/components/SplitForm.js
Free tier users are now limited to the required 3 decks. Paid users who make more than 3 decks who then cancel their subscription will only see their first 3 decks. Rather than try to figure out which 150 cards to limit, cards are temporarily limited to those in the same first 3 decks. Pricing information added to Billing. Some styling changes to modals.
> Limit decks and cards
